#!/bin/sh

DEFAULT_NTP="time.cloudflare.com"
NTP_CONF_FILE="/etc/ntpd.conf"

# move aside original config file
mv -f /etc/ntpd.conf /etc/ntpd.conf.bak

## dynamically populate ntp config file.
{
  echo "# https://github.com/cturra/docker-ntp"
  echo
  echo "# NTP.conf file generated by startup script"
  echo "# located at /opt/startup.sh"
  echo
  echo "listen on *"
  echo
  echo "# time servers provided by NTP_SERVER environment variables."
} > ${NTP_CONF_FILE}


# NTP_SERVERS environment variable is not present, so populate with default server
if [ -z ${NTP_SERVERS} ]; then
  echo "server ${DEFAULT_NTP}" >> ${NTP_CONF_FILE}

# check if list of ntp servers provided in NTP_SERVERS environment variable
# are present and is of greater than length 0.
elif [ $(echo ${#NTP_SERVERS}) > 0 ]; then
  IFS=","
  for n in $NTP_SERVERS; do
    # strip any quotes found before or after ntp server
    echo "server "${n//\"}"" >> ${NTP_CONF_FILE}
  done

# NTP_SERVERS environment variable is present, but doesn't contain ntp servers, so
# populate with a default server.
else
  echo "server ${DEFAULT_NTP}" >> ${NTP_CONF_FILE}
fi


## startup ntpd in the foreground
/usr/sbin/ntpd -v -d -s
