apiVersion: v1
kind: Service
metadata:
  name: ntp-rootless
  namespace: ntp
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ports:
    - name: ntp
      port: 123
      targetPort: ntp
      protocol: UDP
  selector:
    app: ntp-rootless
  type: LoadBalancer # ClusterIP
  loadBalancerClass: ""
  